language: python
python:
  - "3.6"
sudo: false
dist: trusty
install:
  - pip3 install numpy
  - pip3 install feedparser

    
script:
  - bash getjson.sh  
  - bash write_post.sh

after_success:
  - gem install travis -v 1.8.9 --no-rdoc --no-ri
  #- bash trigger-FB-publish.sh

# deploy
deploy:
  - provider: pages    # Deploy master to branch posts
    target-branch: posts
    local-dir: posts_tar
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: true
    on:
      branch: dev
  - provider: pages    # Deploy master to branch gh-pages
    target-branch: master
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    local-dir: web
    keep-history: false
    on:
      branch: dev

