language: generic
sudo: required
dist: trusty
before_install:
  - sudo dpkg -i depend/hugo.deb
cache:
  directories:
    - $TRAVIS_BUILD_DIR/depend
    
script:
  - bash getjson.sh
  - cp -r authors/ web/  # so that RSSparse can get old json #- bash write_post.sh  #- curl --fail "https://raw.githubusercontent.com/Rbloggers/web/posts/posts.tar.gz" > posts.tar.gz #- tar -zxvf posts.tar.gz
  - cd web; tar -zcvf posts.tar.gz _posts; cd - # before: download post.tar.gz then extract
  - mkdir posts_tar; mv web/posts.tar.gz posts_tar/
  # tar.gz web/_post into post_tar/post.tar.gz

# deploy
deploy:
  - provider: pages    # Deploy master to branch posts
    target-branch: posts
    local-dir: posts_tar
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: false
    on:
      branch: master
  - provider: pages    # Deploy master to branch gh-pages
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    local-dir: web
    keep-history: true
    on:
      branch: master

