language: generic
sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get install hugo


script:
  - bash getjson.sh
  - mkdir docs
  - echo "Hello world" > docs/index.md

# deploy
deploy:
  - provider: pages    # Deploy master to branch master
    target-branch: master
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: true
    on:
      branch: master
  - provider: pages    # Deploy master to branch gh-pages
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    local-dir: docs
    keep-history: false
    on:
      branch: master

