language: python
python:
  - "3.6"
sudo: required
dist: trusty
install:
  - pip3 install numpy
  - pip3 install feedparser

    
script:
  - bash getjson.sh  
  - bash write_post.sh

# deploy
deploy:
  - provider: pages    # Deploy master to branch posts
    target-branch: posts
    local-dir: posts_tar
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: true
    on:
      branch: master
  - provider: pages    # Deploy master to branch gh-pages
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    local-dir: web
    keep-history: false
    on:
      branch: master

