language: generic
sudo: required
dist: trusty
before_install:
  - sudo dpkg -i depend/hugo.deb
cache:
  directories:
    - $TRAVIS_BUILD_DIR/depend
    
script:
  - bash getjson.sh
  - mkdir docs
  - echo "Hello world" > docs/index.md

# deploy
deploy:
  - provider: pages    # Deploy master to branch posts
    target-branch: posts
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: false
    on:
      branch: master
  - provider: pages    # Deploy master to branch gh-pages
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    local-dir: docs
    keep-history: true
    on:
      branch: master

