language: generic
sudo: required
dist: trusty
before_install:
  - sudo apt-get update
  - sudo apt-get install hugo


script:
  - bash getjson.sh

# deploy
deploy:
  - provider: pages    # Deploy master to branch win-build
    target-branch: master
    skip-cleanup: true
    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
    keep-history: false
    on:
      branch: master

